import { LifecareDecisionProposalRaw, LifecareSavedDecisionRaw } from '@interfaces/lifecare-decision.interface';
import { buildDecisionUpdate } from '@utils/lifecare-decision';
import { describe, expect, it } from 'vitest';

const MESSAGE =
  '<p style="font-family: \'Times New Roman\'; font-size: 12pt;">Din ans&ouml;kan om f&ouml;rs&ouml;rjningsst&ouml;d enligt 12 Kap 1&sect; SoL&nbsp; Socialtj&auml;nstlagen f&ouml;r period xx-xx har avslagits/delvis avslagits.</p>';

/** The beslutstyp as GetDecision nests it (capture 2026-09-23) — without the `reasons` list. */
const avslagType = {
  code: 152,
  updateSignature: 'TietoEVRY1',
  updateTimestamp: '2025-04-04',
  activeStatus: 1,
  sortOrder: 0,
  name: 'EK Ekonomiskt bistånd 12 kap 1, 7 §§ SoL, avslag',
  type: 10,
  leadsToService: false,
  amountToBalance: false,
  whereDidChildGoMandatory: false,
  canSetAmount: true,
  calculcationRequirement: false,
  includedPersonType: 1,
  reasonType: 2,
  periodType: '',
  coApplicantMandatory: true,
  defaultServiceType: null,
  canIncludePart: false,
  connectToApplicationOptional: false,
  canStartResourceAllocation: false,
  canStopResourceAllocation: false,
  validateCalculationsAreFinalized: false,
  validateDocumentsAreWriteProtected: false,
  checkLMServicePeriod: false,
  leadsToLMAssignment: false,
  leadsToAssignmentIfo: false,
  leadsToAssignment: false,
  leadsToOrderEC: false,
  createAutomaticJournalNote: false,
  createAutomaticJournalNoteIncludingDecisionMessage: false,
  usedForDecisionProposal: false,
  usedForAppeal: false,
  usedForChairDecision: false,
  fromTomNotAllowed: false,
  requiresToDate: false,
  requiresFromDate: false,
  checkLMService: false,
  individualStatisticId: null,
  quantityStatisticId: null,
  processingTimeUntilServiceStarts: 0,
  processingTimeUntilResourceProvided: 0,
  processingTimeUntilExecutionStarts: 0,
  onlyCountWorkingDays: false,
  guardianTypeMandatory: false,
  exceptionFromStatisticsPossible: false,
  isRightScbCodeForService: false,
  lawSectionType: 1,
  showInRefugee: false,
  groups: null,
  isActive: true,
  isInactivated: false,
};

/** Decision/GetDecision?businessType=4&businessId=98 (capture 2026-09-23), in full. */
const saved = (): LifecareSavedDecisionRaw => ({
  decisionId: 98,
  serviceId: 1,
  investigationExecutionId: 0,
  ownerPersonId: '19880209T050',
  decisionCode: 152,
  decisionType: 10,
  date: '2026-09-23',
  fromDate: '',
  toDate: '',
  reasonCode: 0,
  reason: '',
  reasonHeader: '',
  reasonCodeCoApplicant: 0,
  reasonCoApplicant: '',
  reasonHeaderCoApplicant: '',
  decisionMaker: 'RPA_031DEV',
  decisionMakerName: 'RPA_031DEV',
  decisionMakerTitle: 'Automatiserad testhandläggare',
  updateDate: '2026-09-23',
  updateTime: '154221',
  updateSignature: 'RPA_031DEV',
  registrationDate: '2026-09-23',
  registrationSignature: 'RPA_031DEV',
  decisionPersons: [
    {
      decisionId: 98,
      personId: '19880209T050',
      name: 'Testsson, Test',
      personKey: 1,
      coApplicant: false,
      included: false,
      includedTypes: null,
      notificationType: 0,
      notificationTypeText: null,
      notificationDate: '',
      receivedDate: '',
      registeredBy: null,
      personIdFormatted: '880209-T050',
    },
  ],
  decisionParts: [],
  amount: 0,
  coApplicant: null,
  decisionText: 'EK Ekonomiskt bistånd 12 kap 1, 7 §§ SoL, avslag',
  hasDecisionMessage: true,
  hasNoCoApplicant: true,
  hasNotification: false,
  amountToBalance: false,
  bidrTfnr: 0,
  connectedDecisionId: 0,
  uiCanRemit: false,
  uiCanAdjust: false,
  uiCanDelete: true,
  leadsToService: false,
  dontExecute: false,
  type: { ...avslagType },
  decisionSummarys: [],
  refunds: [],
  remitsOrAdjusts: [],
  lifecareCreated: true,
  message: MESSAGE,
  messageIsRevised: false,
  aktualiseringId: null,
  applicationText: '',
  lockedMessage: false,
  typeOfProtocol: null,
  typeOfProtocolText: null,
  sharedCustody: false,
  statisticsException: false,
  doesentLeadsToLMAssignment: false,
  canLeadToLMAssignment: false,
  connectedLMAssignmentId: 0,
  connectedAssignmentIfoId: 0,
  connectedAssignmentIfoIdWithResourceTypeGroup: 0,
  connectedAssignmentId: 0,
  doesentLeadToAssignment: false,
  leadsToOrderEC: false,
  connectedOrderECId: 0,
  status: 0,
  whereDidChildGoType: 0,
  whereDidChildGoTypeText: null,
  guardianType: 0,
  guardianTypeText: null,
  canUnlink: true,
  organisationName: 'Mottagning ekonomiskt bistånd',
  isFromProposal: false,
  proposalText: null,
  workflow: 1,
  canBeSelected: true,
});

/** Only the lists the update is checked against; the blank beslut is not used for a change. */
const proposal: LifecareDecisionProposalRaw = {
  decision: { decisionPersons: [] },
  decisionMakers: [
    { id: 'RPA_031DEV', name: 'RPA_031DEV', title: 'Automatiserad testhandläggare' },
    { id: 'TEST', name: 'Test Handläggare', title: 'Testhandläggare' },
  ],
  decisionTypes: [
    { code: 152, name: 'EK Ekonomiskt bistånd 12 kap 1, 7 §§ SoL, avslag', type: 10, isActive: true, requiresFromDate: false, requiresToDate: false },
    { code: 153, name: 'Ek Ekonomiskt bistånd 12 kap 1, 7 §§ SoL, bifall', type: 0, isActive: true, requiresFromDate: true, requiresToDate: true },
  ],
};

const avslag = { decisionCode: 152, amount: 0, message: MESSAGE, decisionMakerId: 'RPA_031DEV' };

describe('buildDecisionUpdate', () => {
  it('turns the read beslut into exactly the captured Decision/Update body', () => {
    const update = buildDecisionUpdate(saved(), proposal, avslag);

    // Decision/Update?businessType=4&businessId=98 (capture 2026-09-23), field for field and in order.
    // Only updateTime differs from the capture: the read beslut is from a later save than the one captured.
    const capture = {
      decisionId: 98,
      serviceId: 1,
      investigationExecutionId: 0,
      ownerPersonId: '19880209T050',
      decisionCode: 152,
      decisionType: 10,
      date: '2026-09-23',
      fromDate: '',
      toDate: '',
      reasonCode: '',
      reason: '',
      reasonHeader: '',
      reasonCodeCoApplicant: '',
      reasonCoApplicant: '',
      reasonHeaderCoApplicant: '',
      decisionMaker: 'RPA_031DEV',
      decisionMakerName: 'RPA_031DEV',
      decisionMakerTitle: 'Automatiserad testhandläggare',
      updateDate: '2026-09-23',
      updateTime: '154221',
      updateSignature: 'RPA_031DEV',
      registrationDate: '2026-09-23',
      registrationSignature: 'RPA_031DEV',
      decisionPersons: [
        {
          decisionId: 98,
          personId: '19880209T050',
          name: 'Testsson, Test',
          personKey: 1,
          coApplicant: false,
          included: true,
          includedTypes: null,
          notificationTypeText: null,
          notificationDate: '',
          receivedDate: '',
          registeredBy: null,
          personIdFormatted: '880209-T050',
          personIdAndName: '880209-T050, Testsson, Test',
          receivedDateIsInvalid: false,
          isValid: true,
        },
      ],
      decisionParts: [],
      amount: 0,
      coApplicant: 'NOONE',
      decisionText: 'EK Ekonomiskt bistånd 12 kap 1, 7 §§ SoL, avslag',
      hasDecisionMessage: true,
      hasNoCoApplicant: true,
      hasNotification: false,
      amountToBalance: false,
      bidrTfnr: 0,
      connectedDecisionId: 0,
      uiCanRemit: false,
      uiCanAdjust: false,
      uiCanDelete: true,
      leadsToService: false,
      dontExecute: false,
      type: { ...avslagType, reasons: [] },
      decisionSummarys: [],
      refunds: [],
      remitsOrAdjusts: [],
      lifecareCreated: true,
      message: MESSAGE,
      messageIsRevised: false,
      applicationText: '',
      lockedMessage: false,
      typeOfProtocol: null,
      typeOfProtocolText: null,
      sharedCustody: false,
      statisticsException: false,
      doesentLeadsToLMAssignment: false,
      canLeadToLMAssignment: false,
      connectedLMAssignmentId: 0,
      connectedAssignmentIfoId: 0,
      connectedAssignmentIfoIdWithResourceTypeGroup: 0,
      connectedAssignmentId: 0,
      doesentLeadToAssignment: false,
      leadsToOrderEC: false,
      connectedOrderECId: 0,
      status: 0,
      whereDidChildGoTypeText: null,
      guardianTypeText: null,
      canUnlink: true,
      organisationName: 'Mottagning ekonomiskt bistånd',
      isFromProposal: false,
      proposalText: null,
      workflow: 1,
      canBeSelected: true,
    };
    expect(update.writable ? JSON.stringify(update.body) : update.reason).toBe(JSON.stringify(capture));
  });

  it('carries the changed meddelande and names the handläggare who saved it', () => {
    const update = buildDecisionUpdate(saved(), proposal, { ...avslag, message: '<p>Nytt</p>', decisionMakerId: 'test' });

    expect(update.writable && [update.body.message, update.body.decisionMaker, update.body.decisionMakerName]).toEqual([
      '<p>Nytt</p>',
      'TEST',
      'Test Handläggare',
    ]);
  });

  it('refuses a beslut whose meddelande Lifecare has locked', () => {
    expect(buildDecisionUpdate({ ...saved(), lockedMessage: true }, proposal, avslag).writable).toBe(false);
  });

  it('refuses to change the beslutstyp of a registered beslut', () => {
    const update = buildDecisionUpdate(saved(), proposal, { ...avslag, decisionCode: 153, periodFrom: '2026-09-01', periodTo: '2026-09-30' });

    expect(update).toEqual({ writable: false, reason: expect.stringContaining('Beslutstypen kan inte ändras') as string });
  });
});
